### ISSUE TITLE
Channel based meeting links are not working in private messages

### ISSUE THREAD

**Issue by yodapotatofly** [SrMouraSilva/mattermost-google-meet-plugin#2]
When using the plugin in private messages, the resulting link is not working because of the format based on channel. Morover, this format only allows one meeting room per channel, while we might want to have multiple ones.

Going back to uuidv4() is probably better (for my use case at least)

**Comment by SrMouraSilva** [comment]
Thanks for this report. I will check this case.

Maybe a future version admin select can will select for `uuid` or channel base. But for this moment I don't now (yet) how to create the backend server configuration.

**Comment by SrMouraSilva** [comment]
Hi, could you share more details about? I did a test but I can't reproduce it.

**Comment by yodapotatofly** [comment]
It seems to be when the team name is too long. A 13 characters team name results in a 68 characters string, wich breaks google meet link

**Comment by yodapotatofly** [comment]
google meet seems to only accept 60 char long string

**Comment by SrMouraSilva** [comment]
Thanks!
